"""Outbound Hinglish voice recovery calls via Twilio's Voice REST API."""

from __future__ import annotations

import base64
import secrets
from typing import TYPE_CHECKING, Any
from uuid import uuid4
from xml.sax.saxutils import escape

import httpx2

from app.core.config import get_settings
from app.core.constants import (
    OUTREACH_VOICE_COST_PAISE,
    SARVAM_API_BASE,
    SARVAM_TTS_AUDIO_CODEC,
    SARVAM_TTS_LANGUAGE_CODE_HI,
    SARVAM_TTS_MODEL,
    TWILIO_API_BASE,
    TWILIO_VOICE_LANGUAGE_HI,
)
from app.core.logging import get_logger
from app.intervention.tools.base import BaseInterventionTool, ToolExecutionResult
from app.intervention.voice_audio_cache import get_voice_audio_cache

if TYPE_CHECKING:
    from app.audit.models import RecoveryCase
    from app.intervention.models import InterventionPlan

logger = get_logger(__name__)

HTTP_UNAUTHORIZED = 401
SARVAM_MAX_TEXT_CHARS = 2500


def _build_say_twiml(message: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        f'<Response><Say language="{TWILIO_VOICE_LANGUAGE_HI}">{escape(message)}</Say></Response>'
    )


def _build_play_twiml(audio_url: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        f"<Response><Play>{escape(audio_url)}</Play></Response>"
    )


async def _synthesize_with_sarvam(
    message: str, *, client: httpx2.AsyncClient | None = None
) -> bytes | None:
    """Returns None (never raises) so a synthesis problem falls back to
    Twilio's own <Say> instead of blocking the call.
    """
    settings = get_settings()
    api_key = settings.sarvam_api_key
    if not api_key:
        return None

    endpoint = f"{SARVAM_API_BASE}/text-to-speech"
    headers = {
        "api-subscription-key": api_key.get_secret_value(),
        "Content-Type": "application/json",
    }
    body = {
        "text": message[:SARVAM_MAX_TEXT_CHARS],
        "language_code": SARVAM_TTS_LANGUAGE_CODE_HI,
        "speaker": settings.sarvam_tts_speaker,
        "model": SARVAM_TTS_MODEL,
        "output_audio_codec": SARVAM_TTS_AUDIO_CODEC,
    }

    try:
        if client:
            resp = await client.post(endpoint, json=body, headers=headers)
        else:
            async with httpx2.AsyncClient(timeout=30.0) as owned_client:
                resp = await owned_client.post(endpoint, json=body, headers=headers)

        if resp.is_success:
            audios = resp.json().get("audios") or []
            if not audios:
                logger.warning("voice_call.sarvam_empty_response")
                return None
            return base64.b64decode(audios[0])

        logger.warning(
            "voice_call.sarvam_synthesis_failed",
            status_code=resp.status_code,
            response=resp.text,
        )
        return None
    except (httpx2.HTTPError, OSError, ValueError) as exc:
        logger.warning("voice_call.sarvam_synthesis_failed", error=str(exc))
        return None


class VoiceCallTool(BaseInterventionTool):
    """Places a real outbound call through Twilio's Calls API, speaking
    audio pre-generated by Sarvam's Bulbul TTS (code-mixed Hindi/English),
    falling back to Twilio's own <Say> when Sarvam is unconfigured or fails.
    """

    def __init__(self, client: httpx2.AsyncClient | None = None) -> None:
        self._client = client

    async def execute(
        self, case: RecoveryCase, plan: InterventionPlan
    ) -> ToolExecutionResult:
        """Raises if Twilio credentials are missing -- there is no sandbox
        simulation path for a real telephony call.
        """
        settings = get_settings()
        account_sid = settings.twilio_account_sid
        auth_token = settings.twilio_auth_token
        from_number = settings.twilio_from_number

        if not (account_sid and auth_token and from_number):
            msg = "Twilio credentials (account SID, auth token, from number) are not configured"
            logger.warning(
                "voice_call.missing_credentials",
                case_id=case.case_id,
            )
            raise ValueError(msg)

        to_number = case.contact_phone or case.failure_event.contact_phone
        if not to_number:
            msg = f"Case {case.case_id} has no contact_phone for a voice call"
            logger.warning("voice_call.missing_phone_number", case_id=case.case_id)
            raise ValueError(msg)

        message = (
            case.dunning_message_hi
            or plan.dunning_message_hi
            or case.dunning_message_en
            or plan.dunning_message_en
            or f"Namaste, aapka payment of {case.currency} {case.amount_paise / 100:,.2f} "
            "process nahi ho paya. Kripya apna payment retry karein."
        )

        audio_bytes = await _synthesize_with_sarvam(message, client=self._client)
        used_sarvam = audio_bytes is not None
        if audio_bytes is not None:
            token = secrets.token_urlsafe(24)
            get_voice_audio_cache().put(token, audio_bytes)
            audio_url = f"{settings.app_public_base_url}/api/voice-audio/{token}.mp3"
            twiml = _build_play_twiml(audio_url)
        else:
            twiml = _build_say_twiml(message)

        endpoint = f"{TWILIO_API_BASE}/Accounts/{account_sid}/Calls.json"
        form_body = {
            "To": to_number,
            "From": from_number,
            "Twiml": twiml,
        }
        auth = (account_sid, auth_token.get_secret_value())

        logger.info(
            "voice_call.attempt",
            case_id=case.case_id,
            idempotency_key=plan.idempotency_key,
            to_number_suffix=to_number[-4:],
            used_sarvam=used_sarvam,
        )

        try:
            if self._client:
                resp = await self._client.post(endpoint, data=form_body, auth=auth)
            else:
                async with httpx2.AsyncClient(timeout=15.0) as client:
                    resp = await client.post(endpoint, data=form_body, auth=auth)

            if resp.is_success:
                call_data: dict[str, Any] = resp.json()
                call_sid = str(call_data.get("sid", f"CA{uuid4().hex[:32]}"))
                status = str(call_data.get("status", "queued"))
                logger.info(
                    "twilio.api.call_placed",
                    case_id=case.case_id,
                    call_sid=call_sid,
                    status=status,
                )
                payload = {
                    "call_sid": call_sid,
                    "status": status,
                    "to_number_suffix": to_number[-4:],
                    "idempotency_key": plan.idempotency_key,
                    "live_gateway_call": True,
                    "used_sarvam": used_sarvam,
                    "provider_response": call_data,
                }
                return ToolExecutionResult(
                    success=True,
                    action_taken="VOICE_CALL_PLACED",
                    external_id=call_sid,
                    cost_incurred_paise=OUTREACH_VOICE_COST_PAISE,
                    data=payload,
                )

            logger.warning(
                "voice_call.execution_failed",
                case_id=case.case_id,
                status_code=resp.status_code,
                response=resp.text,
            )
            action = (
                "VOICE_CALL_AUTH_ERROR"
                if resp.status_code == HTTP_UNAUTHORIZED
                else "VOICE_CALL_GATEWAY_ERROR"
            )
            return ToolExecutionResult(
                success=False,
                action_taken=action,
                external_id=None,
                cost_incurred_paise=0,
                data={"error": resp.text, "status_code": resp.status_code},
                error_message=resp.text,
            )
        except (httpx2.HTTPError, OSError, ValueError) as exc:
            logger.warning(
                "voice_call.execution_failed", case_id=case.case_id, error=str(exc)
            )
            return ToolExecutionResult(
                success=False,
                action_taken="VOICE_CALL_NETWORK_EXCEPTION",
                external_id=None,
                cost_incurred_paise=0,
                data={"error": str(exc)},
                error_message=str(exc),
            )


__all__ = ["VoiceCallTool"]
